version: '3.8'
services:
  db:
    image: mysql:8.3
    container_name: mysql_bankingvault
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankingvault
      MYSQL_USER: vaultuser
      MYSQL_PASSWORD: vaultpass
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: bankingvault_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bankingvault?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: vaultuser
      SPRING_DATASOURCE_PASSWORD: vaultpass
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
